apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Jaeger 的 OpenTelemetryCollector CR 依赖 OpenTelemetry Operator 提供的 CRD。
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: "https://github.com/satoukick/sre-works.git"
    path: kubernetes/components/jaeger
    targetRevision: main
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
